version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass qt4BLAnrrNSZp2ssRMkLzZjnaZQkcL22
    volumes: 
      - redis:/data
volumes:
  postgres: 
  redis:
