version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres: 
